### ISSUE TITLE
confirm .keys & .values work for MIDIAcccess inputs and outputs

### ISSUE THREAD

**Issue by maks** [jodinathan/js_bindings#10]
Per @jodinathan request in this [comment](https://github.com/dart-lang/sdk/issues/33248#issuecomment-1034806235), I will test and confirm that  `.keys` and `.values` also work for WebMidi API "maps alikes' `input` and `output` properties of `MIDIAccess`

**Comment by jodinathan** [comment]
thanks for the feedback, glad it worked.

I will close this issue. Feel free to open another one if you find anything
