### ISSUE TITLE
Possible issue with fetch?

### ISSUE THREAD

**Issue by gawmanarnar** [jodinathan/js_bindings#11]
I'm trying to use window.fetch but I continue to get a return of _Response instead of window.Response. Am I missing something simple?

`Future<Response> fetchTest() async {
  return window.fetch('https://api.github.com/users/gawmanarnar');
}`

`Error: Expected a value of type 'window.Response', but got one of type '_Response'`

**Comment by jodinathan** [comment]
can you provide more code please?  
My first guess is that it is using `dart:html` version instead

**Comment by gawmanarnar** [comment]
That's what I'm thinking as well. Is there a way to prevent it from doing that?

```dart
import 'package:js_bindings/js_bindings.dart' as bindings;

Future<bindings.Response> fetchTest() async {
  return bindings.window.fetch('https://api.github.com/users/gawmanarnar');
}

void main() async {
  await fetchTest();
}
```

**Comment by jodinathan** [comment]
it seems it is an error with DDC. Works ok with Dart2JS.  

I will make more tests

**Comment by jodinathan** [comment]
I have created an [issue](https://github.com/dart-lang/sdk/issues/48835) in the sdk repo
