### ISSUE TITLE
Example of ShareData

### ISSUE THREAD

**Issue by paul301** [jodinathan/js_bindings#15]
Wonder if I could get any help/example regarding ShareData call

So I have an image that I want to share using it. I have it both as an `ByteData` and `Uint8List`:

    ui.Image image = await boundary.toImage();
    ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    Uint8List pngBytes = byteData!.buffer.asUint8List();

Now when it comes to creating the `Iterable<File>` to pass into the `ShareData` is where I get confused.

    import 'package:js_bindings/js_bindings.dart' as js;

    js.JsIterable<js.File> jsObject = js.JsIterable(   ..something in here I guess?   );

I think the part that's throwing me off if I create an Iterable<File> from flutter core that's not the one this is looking for. But it's not exacly clear how to initialize a JsIterable<File> to be used by this function. Sorry if a bit of a noob question the interop is making my head spin.

**Comment by jodinathan** [comment]
sorry for the late response.
Were you able to make it work?

**Comment by jodinathan** [comment]
@paul301 I am closing this issue.  

please create a new one if need
