### ISSUE TITLE
Static methods not callable

### ISSUE THREAD

**Issue by Ehesp** [jodinathan/js_bindings#25]
Logging as an issue as I'm not sure how to fix. 

It seems static methods are not callable via `callMethod`, for example:

```dart
@JS()
@staticInterop
class Response implements Body {
  external factory Response([dynamic body, ResponseInit? init]);
}

extension PropsResponse on Response {
  static Response json(dynamic data, [ResponseInit? init]) =>
      js_util.callMethod(Response, 'json', [data, init]);
```

Not entirely sure how to call a static method from the JS layer, any ideas?

The error thrown is:

```
NoSuchMethodError: method not found: 'apply' on null
```

Usage is also `interop.PropsResponse.json()`, since you can't access a static on the extension....

**Comment by jodinathan** [comment]
IIRC you could use `js.context['Response']` instead of `Response` directly

**Comment by Ehesp** [comment]
Can't seem to get it working. Strange one.

**Comment by Ehesp** [comment]
Okay so this seems to work:

```dart
@JS()
@staticInterop
class Response implements Body {
  external factory Response([dynamic body, ResponseInit? init]);
  external static json([dynamic body, ResponseInit? init]);
}
```

**Comment by jodinathan** [comment]
hi @Ehesp I've pushed a fix for this issue, https://github.com/jodinathan/js_bindings/issues/26 and https://github.com/jodinathan/js_bindings/issues/24.

The example app ran ok. 

Would you mind do some testing with your apps before I publish to pub please?

**Comment by jodinathan** [comment]
I also removed some forbidden names like `set` and `get`, so there will be no more `mGet` and `mSet`.  
This was needed when I was using factory properties instead of extension methods, now it seem to be fine to use those names.

**Comment by Ehesp** [comment]
Copied from chat for visibility:

Seems to be working apart from one issue 😄 

If we do this for example:

```
fetch('', RequestInit());
```

We'll get an error - it seems as though header is being passed to the constructor as null, which JS says is invalid - it either needs to be undefined or an empty Headers instance. I can fix this by doing: 

```
RequestInit(headers: interop.jsUndefined)
```

However, then we get another error:

```
null is not an accepted type. Expected one of , no-referrer, no-referrer-when-downgrade, same-origin, origin, strict-origin, origin-when-cross-origin, strict-origin-when-cross-origin, unsafe-url.
```

So ReferrerPolicy if not provided also gets passed as null (not undefined), and I can't pass that myself as the type is ReferrerPolicy?
