### ISSUE TITLE
README.md sponsor logo not working

### ISSUE THREAD

**Issue by jarrodcolburn** [jodinathan/js_bindings#28]
Sponsor's logo img does to dead link on README.md and pub.dev

The link old image link https://invertase.io/assets/logo.5d43a55e.svg is 404 error

![Screenshot 2023-03-20 15 21 30](https://user-images.githubusercontent.com/16673615/226456947-921079e4-e02f-4c93-b47e-d39df9b9ea23.png)

**Comment by jarrodcolburn** [comment]
I was gonna PR for another one, but a quick search of their site for a similar SVG only lead me to this https://invertase.io/_astro/logo.5d43a55e.svg which is white letters on transparent background, so not super useful as is on GH's README. And that link might break in the future.
Ask the sponsor for a specific image to add in repo?

**Comment by jodinathan** [comment]
fixed, thanks
