### ISSUE TITLE
Add (GitHub) CI support!

### ISSUE THREAD

**Issue by kevmoo** [jodinathan/js_bindings#4]
Would be great for folks submitting PRs. Happy to help!

**Comment by jodinathan** [comment]
I guess we could add the bindings to .gitignore and make the CI execute the scripts to generate them.
Can anyone help with this? I am not very experienced in this matter

**Comment by jodinathan** [comment]
done.
Thanks to the dart team for the [action](https://github.com/dart-lang/setup-dart) now the bindings are generated through a github action
