### ISSUE TITLE
how to iterate a MIDIInputMap ?

### ISSUE THREAD

**Issue by maks** [jodinathan/js_bindings#9]
Hi thank you for making this fantastic package!

Using the latest `0.0.4+4` and master channel on Flutter seems to work fine.
But I'm trying to use this with Chrome for WebMidi and I'm stuck in trying to figure out how to iterate over the `MIDIInputMap` map. eg I'd would like to do something like:

```
Future<void> _initMidi() async {
    final a = await html.window.navigator.requestMIDIAccess();
    print('got MIdiAccess: ${a.inputs}');
    for (var i in a.inputs) {
      print('midi input:$i');
    }
  }
```
but the MIDIInputMap is not a iterable and I can't see any extensions on it to allow iterating over the underlying JS object?

**Comment by jodinathan** [comment]
thanks for filling the issue

fixed it by making maplike js types to extend the JsMap extension.

published as 0.0.5

closing.  
Create another issue if you find anything
